services:
    redis:
        image: "redis/redis-stack-server:latest"
        ports:
            - "6379:6379"
        volumes:
            - splat3api-redis-volume:/datas
            - "./src/configs/redis.conf:/etc/redis.conf"

volumes:
    splat3api-redis-volume:
