services:
    redis:
        image: 'redis/redis-stack-server:latest'
        container_name: splat3-api-redis
        ports:
            - '6379:6379'
        volumes:
            - splat3api-redis-volume:/datas
            - './src/configs/redis.conf:/etc/redis.conf'

        networks:
            - splat3-api

volumes:
    splat3api-redis-volume:

networks:
    splat3-api:
        external: true
